config/routes.rb
Rails.application.routes.draw do

  resources :subscriptions
  resources :blogs 
  mount Ckeditor::Engine => '/ckeditor'
  resources :abouts
  devise_for :users
  
  get 'logos/index'
  	root 'logos#index'
  	resources :order_statuses
  	resource :cart, only: [:show]
  	resources :order_items, only: [:create, :update, :destroy]
  	resources :orders
  	resources :logos 
    resources :searches 
    get 'home/index'
    get 'home/account'
    get 'home/contact'
    get 'home/need_custom_logo'
  post 'home/contact_us_mailer' 
end

app/models/about.rb
class About < ApplicationRecord
	mount_uploader :avatar, AvatarUploader
end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :question, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	mount_uploader :avatar, AvatarUploader
	has_many :questions, :dependent => :destroy
  accepts_nested_attributes_for :questions, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :logos
end

app/models/logo.rb
class Logo < ApplicationRecord
  has_many :subscriptions
    mount_uploader :avatar, AvatarUploader
    belongs_to :order, optional: true
	has_many :order_items
  belongs_to :category, optional: true
  # default_scope { where(active: true) }
    def self.search(name)
      if name
        where('name LIKE ?', "%#{name}%")
      else
        all
      end
    end
end

app/models/order.rb
class Order < ApplicationRecord
	 belongs_to :order_status, optional: true
  has_many :order_items
  before_create :set_order_status
  has_many :logos
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:sub_total] = sub_total
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :logo, optional: true
  belongs_to :order, optional: true

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :logo_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      logo.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def logo_present
    if logo.nil?
      errors.add(:logo, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
	 has_many :orders
end

app/models/question.rb
class Question < ApplicationRecord
	belongs_to :blog, optional: true
	belongs_to :search, optional: true
  	has_many :answers, :dependent => :destroy
  	accepts_nested_attributes_for :answers, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

end

app/models/search.rb
class Search < ApplicationRecord
	has_many :questions, :dependent => :destroy
    accepts_nested_attributes_for :questions, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

	def self.search(name)
      if name
        where('name LIKE ?', "%#{name}%")
      else
        all
      end
    end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
	belongs_to :order_item
  	validates_presence_of :order_item_id
	validates_presence_of :email

	attr_accessor :stripe_card_token

	def save_with_payment
	    if valid?
	      customer = Stripe::Customer.create(description:email, order_item: order_item_id, card: stripe_card_token)
	      self.stripe_customer_token = customer.id
	      save!
	    end
	  	rescue Stripe::InvalidRequestError => e
 			logger.error "Stripe error while creating customer: #{e.message}"
  			errors.add :base, "There was a problem with your credit card."
  	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
      8.times do
        question = @blog.questions.build
        1.times { question.answers.build }
      end
  end

  # GET /blogs/1/edit
  def edit
    
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :description, :avatar, :recentposts,  questions_attributes: [:id, :content, :_destroy, answers_attributes: [:id, :content, :_destroy]])
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logos_helper.rb
module LogosHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/blogs/_answer_fields.html.erb
<p>
  <%= f.label :content, "Answer" %>
  <%= f.text_area :content, :class => 'form-control ckeditor' %>
  <%= f.check_box :_destroy %>
  <%= f.label :_destroy, "Remove" %>
</p>

app/views/blogs/_form.html.erb
<%= form_for @blog do |f| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.fields_for :questions do |builder| %>
    <%= render "question_fields", :f => builder %>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, id: :blog_title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, id: :blog_description, :class => 'form-control ckeditor' %>
  </div>

  <div class="field">
    <%#= f.label :avatar %>
    <%#= f.file_field :avatar %>
  </div>

  <div class="field">
    <%= f.label :recentposts %>
    <%= f.text_field :recentposts, id: :blog_recentposts %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/_question_fields.html.erb
<p>
  <%= f.label :content, "Question" %><br />
  <%= f.text_area :content, :rows => 3 %><br />
  <%= f.check_box :_destroy %>
  <%= f.label :_destroy, "Remove Question" %>
</p>
<%= f.fields_for :answers do |builder| %>
  <%= render 'answer_fields', :f => builder %>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<div class="container">
  <div class="column">
    <% @blogs.each do |blog| %>
      <div class= "col-md-8">
        <% for question in blog.questions %>
          <h1 style="font-size:30px;" >
            <b><%= h question.content %></b><br><br>
            </h1>
          
            <% for answer in question.answers %>
             <p style="font-size:15px; color:grey;"><%= h answer.content.html_safe %></p><br>
            <% end %>
        <% end %>
      </div>
      <div class= "col-md-4">
          <p style="font-size:20px;" >
            <b><%= blog.title %></b>
          </p><br>

          <p style="font-size:15px; color:grey;">
            <%= blog.description.html_safe %>
          </p><br>

          <p>
            <%#= image_tag @blog.avatar.url %>
          </p>
            
          <p>
            <strong style="font-size:20px;">Recent Posts</strong><br><br>
              <ul>
                <li><p style="font-size:15px;"><b><%= blog.recentposts %></b></p></li>
              </ul>
          </p>
        </div>
    <% end %>
  </div>
</div>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<div class="container">
  <div class="column">
    <div class= "col-md-8">
      <% for question in @blog.questions %>
        <h1 style="font-size:30px;" >
          <b><%= h question.content %></b><br><br>
          </h1>
        
          <% for answer in question.answers %>
           <p style="font-size:15px; color:grey;"><%= h answer.content.html_safe %></p><br>
          <% end %>
        
      <% end %>
    </div>
      <div class= "col-md-4">
          <p style="font-size:20px;" >
            <b><%= @blog.title %></b>
          </p><br>

          <p style="font-size:15px; color:grey;">
            <%= @blog.description.html_safe %>
          </p><br>

          <p>
            <%#= image_tag @blog.avatar.url %>
          </p>
            
          <p>
            <strong style="font-size:20px;">Recent Posts</strong><br><br>
              <ul>
                <li><p style="font-size:15px;"><b><%= @blog.recentposts %></b></p></li>
              </ul>
          </p>

            <%= link_to 'Edit', edit_blog_path(@blog) %> |
            <%= link_to 'Back', blogs_path %>
            <%= link_to 'Destroy', @blog, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
  </div>
</div>
<%= link_to 'New Blog', new_blog_path %>