config/routes.rb
Rails.application.routes.draw do

  resources :subscriptions
  resources :blogs 
  mount Ckeditor::Engine => '/ckeditor'
  resources :abouts
  devise_for :users
  
  get 'logos/index'
  	root 'logos#index'
  	resources :order_statuses
  	resource :cart, only: [:show]
  	resources :order_items, only: [:create, :update, :destroy]
  	resources :orders
  	resources :logos 
    resources :searches 
    get 'home/index'
    get 'home/account'
    get 'home/contact'
    get 'home/need_custom_logo'
  post 'home/contact_us_mailer' 
end

app/models/about.rb
class About < ApplicationRecord
	mount_uploader :avatar, AvatarUploader
end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :question, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	mount_uploader :avatar, AvatarUploader
	has_many :questions, :dependent => :destroy
  accepts_nested_attributes_for :questions, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :logos
end

app/models/logo.rb
class Logo < ApplicationRecord
  has_many :subscriptions
    mount_uploader :avatar, AvatarUploader
    belongs_to :order, optional: true
	has_many :order_items
  belongs_to :category, optional: true
  # default_scope { where(active: true) }
    def self.search(name)
      if name
        where('name LIKE ?', "%#{name}%")
      else
        all
      end
    end
end

app/models/order.rb
class Order < ApplicationRecord
	 belongs_to :order_status, optional: true
  has_many :order_items
  before_create :set_order_status
  has_many :logos
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:sub_total] = sub_total
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :logo, optional: true
  belongs_to :order, optional: true

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :logo_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      logo.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def logo_present
    if logo.nil?
      errors.add(:logo, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
	 has_many :orders
end

app/models/question.rb
class Question < ApplicationRecord
	belongs_to :blog, optional: true
	belongs_to :search, optional: true
  	has_many :answers, :dependent => :destroy
  	accepts_nested_attributes_for :answers, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

end

app/models/search.rb
class Search < ApplicationRecord
	has_many :questions, :dependent => :destroy
    accepts_nested_attributes_for :questions, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

	def self.search(name)
      if name
        where('name LIKE ?', "%#{name}%")
      else
        all
      end
    end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
	belongs_to :order_item
  	validates_presence_of :order_item_id
	validates_presence_of :email

	attr_accessor :stripe_card_token

	def save_with_payment
	    if valid?
	      customer = Stripe::Customer.create(description:email, order_item: order_item_id, card: stripe_card_token)
	      self.stripe_customer_token = customer.id
	      save!
	    end
	  	rescue Stripe::InvalidRequestError => e
 			logger.error "Stripe error while creating customer: #{e.message}"
  			errors.add :base, "There was a problem with your credit card."
  	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save_with_payment
        format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      params.require(:subscription).permit(:email, :card_number, :card_code, :card_month)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logos_helper.rb
module LogosHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= form_for @subscription do |form| %>
  <% if subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
      <% subscription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>

  <%= form.hidden_field :stripe_card_token %>
    <div class="col-sm-8">
      <div class="field">
        <h4> Email Address *</h4>
        <%= form.text_field :email, id: :subscription_email, placeholder: "Enter Email", class: "form-control" %>
      </div>
    </div><br>
    <% if @subscription.stripe_card_token %>
        Credit card has been provided
        <% else %>
          <div class="col-sm-8">
            <div class="field">
              <h4> Credit Card Number* </h4>
              <%= form.text_field :card_number, id: :subscription_card_number, placeholder: "Card Number", class: "form-control" %>
            </div>
          </div><br>
          <div class="col-sm-8">
            <div class="field">
              <h4>Security Code on Card (CVV)* </h4>
              <%= form.text_field :card_code, id: :subscription_card_code, placeholder: "security code", class: "form-control" %>
            </div>
          </div><br>
          <div class="col-sm-8">
            <div class="field">
              <h4>Expiration (MM/YY)* </h4>
              <%= select_month nil, {add_month_numbers_true: true}, {name: nil, id: "card_month"}%>
              <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year"} %>
            </div>
          </div><br>
      <% end %>
      <!-- Form fields omitted -->
      <div id="stripe_error">
        <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
      </div>
      <div class="col-sm-8">
      <div class="actions"><br>
        <%= form.submit "Subscribe" %>
      </div>
    </div>
  <% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing Subscription</h1>

<%= render 'form', subscription: @subscription %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subscriptions</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Card number</th>
      <th>Card code</th>
      <th>Card month</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= subscription.email %></td>
        <td><%= subscription.card_number %></td>
        <td><%= subscription.card_code %></td>
        <td><%= subscription.card_month %></td>
        <td><%= link_to 'Show', subscription %></td>
        <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
        <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<center><h1>Payment Options</h1><br></center>
	<%= render 'form', subscription: @subscription %>

	

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @subscription.email %>
</p>

<p>
  <strong>Card number:</strong>
  <%= @subscription.card_number %>
</p>

<p>
  <strong>Card code:</strong>
  <%= @subscription.card_code %>
</p>

<p>
  <strong>Card month:</strong>
  <%= @subscription.card_month %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>