config/routes.rb
Rails.application.routes.draw do

  resources :subscriptions
  resources :blogs 
  mount Ckeditor::Engine => '/ckeditor'
  resources :abouts
  devise_for :users
  
  get 'logos/index'
  	root 'logos#index'
  	resources :order_statuses
  	resource :cart, only: [:show]
  	resources :order_items, only: [:create, :update, :destroy]
  	resources :orders
  	resources :logos 
    resources :searches 
    get 'home/index'
    get 'home/account'
    get 'home/contact'
    get 'home/need_custom_logo'
  post 'home/contact_us_mailer' 
end

app/models/about.rb
class About < ApplicationRecord
	mount_uploader :avatar, AvatarUploader
end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :question, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	mount_uploader :avatar, AvatarUploader
	has_many :questions, :dependent => :destroy
  accepts_nested_attributes_for :questions, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :logos
end

app/models/logo.rb
class Logo < ApplicationRecord
  has_many :subscriptions
    mount_uploader :avatar, AvatarUploader
    belongs_to :order, optional: true
	has_many :order_items
  belongs_to :category, optional: true
  # default_scope { where(active: true) }
    def self.search(name)
      if name
        where('name LIKE ?', "%#{name}%")
      else
        all
      end
    end
end

app/models/order.rb
class Order < ApplicationRecord
	 belongs_to :order_status, optional: true
  has_many :order_items
  before_create :set_order_status
  has_many :logos
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:sub_total] = sub_total
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :logo, optional: true
  belongs_to :order, optional: true

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :logo_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      logo.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def logo_present
    if logo.nil?
      errors.add(:logo, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
	 has_many :orders
end

app/models/question.rb
class Question < ApplicationRecord
	belongs_to :blog, optional: true
	belongs_to :search, optional: true
  	has_many :answers, :dependent => :destroy
  	accepts_nested_attributes_for :answers, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

end

app/models/search.rb
class Search < ApplicationRecord
	has_many :questions, :dependent => :destroy
    accepts_nested_attributes_for :questions, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

	def self.search(name)
      if name
        where('name LIKE ?', "%#{name}%")
      else
        all
      end
    end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
	belongs_to :order_item
  	validates_presence_of :order_item_id
	validates_presence_of :email

	attr_accessor :stripe_card_token

	def save_with_payment
	    if valid?
	      customer = Stripe::Customer.create(description:email, order_item: order_item_id, card: stripe_card_token)
	      self.stripe_customer_token = customer.id
	      save!
	    end
	  	rescue Stripe::InvalidRequestError => e
 			logger.error "Stripe error while creating customer: #{e.message}"
  			errors.add :base, "There was a problem with your credit card."
  	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/logos_controller.rb
class LogosController < ApplicationController
  before_action :set_logo, only: [:show, :edit, :update, :destroy]

  # GET /logos
  # GET /logos.json
  def index
    @logos = Logo.all
     @logos = Logo.search(params[:name])
      @order_item = current_order.order_items.new
  end

  # GET /logos/1
  # GET /logos/1.json
  def show
    @order_item = current_order.order_items.new
  end

  # GET /logos/new
  def new
    @logo = Logo.new
    @categories = Category.all.map{|c| [c.name, c.id]}
  end

  # GET /logos/1/edit
  def edit
  end

  # POST /logos
  # POST /logos.json
  def create
    @logo = Logo.new(logo_params)
    @logo.category_id = params[:category_id]

    respond_to do |format|
      if @logo.save
        format.html { redirect_to @logo, notice: 'Logo was successfully created.' }
        format.json { render :show, status: :created, location: @logo }
      else
        format.html { render :new }
        format.json { render json: @logo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logos/1
  # PATCH/PUT /logos/1.json
  def update
    respond_to do |format|
      if @logo.update(logo_params)
        format.html { redirect_to @logo, notice: 'Logo was successfully updated.' }
        format.json { render :show, status: :ok, location: @logo }
      else
        format.html { render :edit }
        format.json { render json: @logo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logos/1
  # DELETE /logos/1.json
  def destroy
    @logo.destroy
    respond_to do |format|
      format.html { redirect_to logos_url, notice: 'Logo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_logo
      @logo = Logo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def logo_params
      params.require(:logo).permit(:name, :avatar, :price, :order_id, :description, :cart_id, :category_id, :quantity)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logos_helper.rb
module LogosHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/logos/_form.html.erb
<%= form_for @logo, html: { multipart: true } do |form| %>
  <% if logo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(logo.errors.count, "error") %> prohibited this logo from being saved:</h2>

      <ul>
      <% logo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :avatar %>
   <%= form.file_field :avatar %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :logo_name %>
  </div>
  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/logos/edit.html.erb
<h1>Editing Logo</h1>

<%= render 'form', logo: @logo %>

<%= link_to 'Show', @logo %> |
<%= link_to 'Back', logos_path %>

app/views/logos/index.html.erb
<p id="notice"><%= notice %></p>
<div class= "container-fluid">
  <center>
    <h1 style="font-size:30px;"><b>logos for sale!</b></h1>
    <h1 style="font-size:30px; color:grey;">All logos $350! Purchase one and you alone own it. When a logo is purchased it sells out.</h1>
  </center>
  <div class="container">
    <div class="row">
      <% @logos.each do |logo| %>
        <div class="col-xs-3">
          <a href="/logos/<%= logo.id %>"><%= image_tag logo.avatar.url, class: "img-responsive thumbnail", width: "90", height: "90"  %></a>
        </div>
      <% end %>
    </div>
  </div>
  <br>
 
</div>

app/views/logos/new.html.erb
<h1>New Logo</h1>

<%= render 'form', logo: @logo %>

<%= link_to 'Back', logos_path %>

app/views/logos/show.html.erb
<p id="notice"><%= notice %></p>
<div class= container>
  <center>
   <h1 style="font-size:30px;"><b><%= @logo.name %></b></h1>
  </center><br>

  <p>
    <%= image_tag @logo.avatar.url %>
  </p><br>

  <p>
    <h1 style="font-size:20px;"><%= @logo.description %></h1>
  </p>

  <%= form_for @order_item, remote: true do |f| %>
    <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency @logo.price %></span></h4>
    <div class="input-group">
      <%= f.number_field :quantity, value: 0, min: 0 %>
      <div class="input-group-btn">
        <%= f.hidden_field :logo_id, value: @logo.id %>
        <%= f.submit "add_to_cart", class: "btn btn-primary" %>
      </div>
      <div class="input-group-btn">
        <%= link_to "Buy Now", orders_path, class: "btn btn-link", class: "btn btn-danger"%>
      </div>
    </div>
  <% end %>
  <%= link_to 'Edit', edit_logo_path(@logo) %> |
  <%= link_to 'Destroy', logo_path(@logo),
        method: :delete,
        data: { confirm: 'Are you sure?' } %>
  <%= link_to 'Back', logos_path %>
</div>