config/routes.rb
Rails.application.routes.draw do

  resources :subscriptions
  resources :blogs 
  mount Ckeditor::Engine => '/ckeditor'
  resources :abouts
  devise_for :users
  
  get 'logos/index'
  	root 'logos#index'
  	resources :order_statuses
  	resource :cart, only: [:show]
  	resources :order_items, only: [:create, :update, :destroy]
  	resources :orders
  	resources :logos 
    resources :searches 
    get 'home/index'
    get 'home/account'
    get 'home/contact'
    get 'home/need_custom_logo'
  post 'home/contact_us_mailer' 
end

app/models/about.rb
class About < ApplicationRecord
	mount_uploader :avatar, AvatarUploader
end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :question, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	mount_uploader :avatar, AvatarUploader
	has_many :questions, :dependent => :destroy
  accepts_nested_attributes_for :questions, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :logos
end

app/models/logo.rb
class Logo < ApplicationRecord
  has_many :subscriptions
    mount_uploader :avatar, AvatarUploader
    belongs_to :order, optional: true
	has_many :order_items
  belongs_to :category, optional: true
  # default_scope { where(active: true) }
    def self.search(name)
      if name
        where('name LIKE ?', "%#{name}%")
      else
        all
      end
    end
end

app/models/order.rb
class Order < ApplicationRecord
	 belongs_to :order_status, optional: true
  has_many :order_items
  before_create :set_order_status
  has_many :logos
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:sub_total] = sub_total
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :logo, optional: true
  belongs_to :order, optional: true

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :logo_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      logo.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def logo_present
    if logo.nil?
      errors.add(:logo, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
	 has_many :orders
end

app/models/question.rb
class Question < ApplicationRecord
	belongs_to :blog, optional: true
	belongs_to :search, optional: true
  	has_many :answers, :dependent => :destroy
  	accepts_nested_attributes_for :answers, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

end

app/models/search.rb
class Search < ApplicationRecord
	has_many :questions, :dependent => :destroy
    accepts_nested_attributes_for :questions, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

	def self.search(name)
      if name
        where('name LIKE ?', "%#{name}%")
      else
        all
      end
    end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
	belongs_to :order_item
  	validates_presence_of :order_item_id
	validates_presence_of :email

	attr_accessor :stripe_card_token

	def save_with_payment
	    if valid?
	      customer = Stripe::Customer.create(description:email, order_item: order_item_id, card: stripe_card_token)
	      self.stripe_customer_token = customer.id
	      save!
	    end
	  	rescue Stripe::InvalidRequestError => e
 			logger.error "Stripe error while creating customer: #{e.message}"
  			errors.add :base, "There was a problem with your credit card."
  	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logos_helper.rb
module LogosHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items (#{number_to_currency current_order.sub_total})", cart_path, class: "btn btn-link" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LogoApp</title>
    <%= csrf_meta_tags %>
	<%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<%= javascript_include_tag "https://js.stripe.com/v1/", "application" %>
	<%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
	<style >
		.thumbnail{
		     border:none !important;
		     background: transparent !important;
		     box-shadow:none !important;
		  }

	</style>
  </head>
	<body>
	    <br><br>
	  	<nav class="navbar">
		  <div class="container">
		    <nav class="navbar navbar-light bg-faded">
			  <div class="navbar-brand">
			  	<div class= "row">
			  		<%= image_tag "logo.jpg", width: "30", height:"30", class: "d-inline-block align-top" %><b><%= link_to "Bootstrap Logos", logos_path %></b></h3>
			    </div>
			  </div>
			  	<ul class="nav navbar-nav navbar-right">
			      	<li><%= link_to 'Account', home_account_path %></li>
			     	<li><%= image_tag "cart.png", width: "30", height:"30" %></li><li><%= render 'layouts/cart_text' %></li>
			 <!-- search button -->
    				<li><%= form_tag(searches_path, method: :get) do %>
  							<%= text_field_tag :name, params[:term]%>
  							<%= submit_tag 'Search' %>
						<% end %></li>
		    	</ul>
			</nav>
		    <ul class="nav navbar-nav ">
		      <li style="font-size:15px; color:grey;"><%= link_to 'How It Works', search_path(1) %></li>
		      <li style="font-size:15px; color:grey;"><%= link_to 'About', abouts_path %></li>
		      <li style="font-size:15px; color:grey;"><%= link_to 'Blog', blogs_path %></li>
		      <li style="font-size:15px; color:grey;"><%= link_to 'Contact', home_contact_path %></li>
		      <li><i class="fa fa-star"></i><li style="font-size:15px; color:grey;"><%= link_to 'Need a Custom Logo?', home_need_custom_logo_path %></li></li>
		    </ul>
		  </div>
		</nav>

		<div class="container">
			<%= yield %>
		</div>

		<br><br>
		<div class= "container">
		    <div class= col-md-4>
	    		<p style="font-size:20px;"><b>Bootstrap Logos</b></p><br>
	    		<p style="color:grey;">Off the shelf logos. For builders, makers, and people with big dreams but small budgets.</p>
	    		<p style="color:grey;">Bootstrap logos is a product by Kyle Lambert (@calloutcreative).</p>
	    		<a href="https://www.facebook.com/login.php?next=https%3A%2F%2Fwww.facebook.com%2Fplugins%2Ferror%2Fconfirm%2Flike%3Fiframe_referer%3Dhttps%253A%252F%252Fbootstraplogos.com%252F%26kid_directed_site%3Dfalse%26secure%3Dtrue%26plugin%3Dlike%26return_params%3D%257B%2522href%2522%253A%2522https%253A%252F%252Fwww.facebook.com%252Fbootstraplogos%252F%2522%252C%2522width%2522%253A%2522133%2522%252C%2522layout%2522%253A%2522button_count%2522%252C%2522action%2522%253A%2522like%2522%252C%2522size%2522%253A%2522large%2522%252C%2522show_faces%2522%253A%2522false%2522%252C%2522share%2522%253A%2522true%2522%252C%2522height%2522%253A%252246%2522%252C%2522appId%2522%253A%2522311040578935330%2522%252C%2522ret%2522%253A%2522sentry%2522%252C%2522act%2522%253A%2522like%2522%257D">

				<button class="btn btn-primary"><i class="fa fa-thumbs-up">Like</i> </button></a>
				<a href="https://www.facebook.com/login.php?skip_api_login=1&api_key=311040578935330&signed_next=1&next=https%3A%2F%2Fwww.facebook.com%2Fsharer%2Fsharer.php%3Fu%3Dhttps%253A%252F%252Fwww.facebook.com%252Fbootstraplogos%252F%26display%3Dpopup%26ref%3Dplugin%26src%3Dlike%26kid_directed_site%3D0%26app_id%3D311040578935330&cancel_url=https%3A%2F%2Fwww.facebook.com%2Fdialog%2Freturn%2Fclose%3Ferror_code%3D4201%26error_message%3DUser%2Bcanceled%2Bthe%2BDialog%2Bflow%23_%3D_&display=popup&locale=en_GB&kid_directed_site=0">

				<button class="btn btn-primary">Share</button></a>
	    	</div>
	    	<div class= col-md-4>
	    		<p style="font-size:20px;"><b>Menu</b></p><br>
	    		<ul>
	    		<li><%= link_to 'How It Works', search_path(1) %></li>
			    <li><%= link_to 'About', about_path(1) %></li>
			    <li><%= link_to 'Blog', blog_path(1) %></li>
			    <li><%= link_to 'Contact', home_contact_path %></li>
			    <li><i class="fa fa-star"></i><%= link_to 'Need a Custom Logo?', home_need_custom_logo_path %></li>   
			    </ul>	
			</div>
			<div class= col-md-4>
				<p id="notice"><%= notice %></p>
				<p style="font-size:20px;"><b>Sign up for email updates!</b></p><br>
				<p style="color:grey;">Get notified when new logos become available</p>
				<h2>Sign up</h2>
                <%= render 'users/registrations/new' %>
            </div>
    	</div>
    	<footer>
			<div class="footer-copyright">
			    <div class="container">
			      <center>
			        <h1 style="font-size:18px; color: #666;">
			          Copyright © 2017 Bootstrap Logos  
			        </h1>
			      </center>
			    </div>
			</div>
		</footer>
	</body>
</html>